
###########################
#			HEAL	      #
###########################
heal-amount: 20.0
heal-message: "&aYou have been healed"

###########################
#	    	FEED	      #
###########################
feed-amount: 20
feed-message: "&aYou have been feeded"

###########################
#         PLAYER          #
###########################
player:
	notFound: "&4Player not found!"
	noPerms: "&4You don't have the permission to execute this command"